function createUI(){
 const host=document.createElement('div');host.id='bqm-launch';host.dataset.version=VERSION;
 const root=host.attachShadow({mode:'open'});document.body.append(host);
 root.innerHTML=`<style>
 :host{font:14px/1.65 system-ui,"Microsoft YaHei",sans-serif;color:#253248;position:relative;z-index:2147483646}*{box-sizing:border-box}[hidden]{display:none!important}button,input,select{font:inherit}button{cursor:pointer;border:1px solid #d9e0eb;border-radius:9px;background:white;padding:9px 14px;color:#253248}button:hover{background:#edf1f8}button:disabled{opacity:.5;cursor:wait}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #ba4380;outline-offset:2px}input,select{border:1px solid #ccd5e3;border-radius:6px;padding:6px;background:#fff;color:#253248}a{color:#b93e76}.muted{color:#697890;font-size:12px}.primary{background:#c84b86;color:#fff;border-color:#c84b86}.primary:hover{background:#ad376f}.danger{color:#b73546}#launch{position:fixed;right:22px;bottom:22px;background:#c84b86;color:#fff;box-shadow:0 5px 24px #0003}#shade{position:fixed;inset:0;background:#18202dbb;display:flex;align-items:center;justify-content:center;padding:20px}#panel{width:1020px;max-width:100%;max-height:95vh;overflow:auto;background:#fafbfe;border-radius:18px;padding:24px;box-shadow:0 20px 90px #0005}header,footer,.row,.scores,.actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap}header{justify-content:space-between;border-bottom:1px solid #e2e7ef;padding-bottom:12px}h2{font-size:24px;line-height:1.4;margin:8px 0}h3{margin:12px 0 8px;font-size:16px}#source{padding:12px 0;border-bottom:1px solid #e2e7ef}#source-url{flex:1;min-width:190px}#content{display:grid;grid-template-columns:220px 1fr;gap:24px;margin:20px 0}#cover{width:220px;max-height:320px;object-fit:contain;border-radius:10px;background:#edf0f5}#summary{white-space:pre-line;max-height:145px;overflow:auto;margin:12px 0;font-size:13px;overscroll-behavior:contain}#existing{font-weight:600;margin-top:10px}.scores{margin:12px 0;gap:7px}.scores button{min-width:46px}.actions button{flex:1}#status{min-height:25px;color:#a6386d;margin:10px 0}footer{margin-top:14px}#rank{width:95px}#failures{max-height:150px;overflow:auto}.failed{padding:6px 0;border-bottom:1px solid #e2e7ef}.failed span{display:block}.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.settings-grid label{display:flex;gap:8px;align-items:center;justify-content:space-between}.settings-grid input:not([type=checkbox]),.settings-grid select{width:155px}#settings{padding-top:10px}#settings-error{color:#b73546;min-height:22px}.button-setting{display:grid;grid-template-columns:80px 1fr 125px 70px;gap:8px;margin:8px 0}.button-setting input{min-width:0;width:100%}#import-file{max-width:240px}#queue-details{margin-top:8px}#queue-items{max-height:150px;overflow:auto}#hint{font-size:12px;color:#697890}#credit{margin-left:auto}#modal{position:absolute;inset:0;background:#172132a8;display:flex;align-items:center;justify-content:center}#modal-box{background:white;padding:24px;border-radius:12px;max-width:480px;margin:20px}#panel{position:relative}#source-title{width:100%}
 #content:has(#cover[hidden]){grid-template-columns:1fr}.button-setting input[type=checkbox]{width:auto}.button-setting label{display:flex;align-items:center;gap:5px}.settings-grid input[id^=bind-]{width:210px;max-width:60%}
 @media(max-width:650px){#content{grid-template-columns:1fr}#cover{width:130px;max-height:180px}#panel{padding:14px}#shade{padding:6px}.settings-grid{grid-template-columns:1fr}.button-setting{grid-template-columns:60px 1fr 100px 50px}}
 </style><button id="launch">▶ 快速补标</button><div id="shade" hidden><section id="panel" role="dialog" aria-modal="true" aria-label="Bangumi 快速补标">
 <header><div><strong>Bangumi 快速补标</strong><div id="hint"></div></div><div class="row"><button id="settings-open">设置</button><button id="close">暂停 / 关闭</button></div></header>
 <section id="main"><div id="source" class="row"><select id="category" aria-label="分类">${Object.entries(TYPES).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}<option value="comic">漫画</option></select><select id="sort" aria-label="排序">${Object.entries(SORTS).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><button id="source-apply">切换列表</button><button id="source-current">使用当前网页列表</button><div class="row" style="width:100%"><input id="timeline-user" aria-label="他人用户名或时间胶囊地址" placeholder="他人用户名或时间胶囊地址" style="flex:1;min-width:190px"><button id="timeline-apply">浏览其评分动画</button></div><details style="width:100%"><summary>筛选列表地址</summary><div class="row"><input id="source-url" aria-label="列表地址" placeholder="粘贴 Bangumi 分类浏览页地址，保留筛选"><button id="source-url-apply">使用地址</button></div></details><span id="source-title" class="muted"></span></div>
 <div id="content"><img id="cover" alt="作品封面"><div><span id="position" class="muted"></span><h2 id="title">准备开始</h2><div id="original" class="muted"></div><div id="info"></div><div id="existing"></div><div id="summary"></div><a id="detail" target="_blank" rel="noopener">打开作品详情 ↗</a></div></div>
 <div id="score-label" class="muted"></div><div class="scores">${Array.from({length:10},(_,i)=>`<button data-score="${i+1}">${i+1}</button>`).join('')}</div><div id="actions" class="actions"></div>
 <div id="status" role="status" aria-live="polite"></div><div id="queue" class="muted" role="status"></div><div id="failures"></div><details id="queue-details"><summary>保存队列详情</summary><div id="queue-items"></div></details>
 <footer><button id="retry">重新加载</button><label><span id="jump-label">Rank</span> <input id="rank" type="number" min="1"></label><button id="jump">前往</button><span class="muted">位置自动记忆</span></footer></section>
 <section id="settings" hidden><h3>操作与预加载</h3><div class="settings-grid"><label>默认评分 <input id="setting-score" type="number" min="1" max="10"></label><label>后面预加载 <input id="setting-ahead" type="number" min="0" max="20"></label><label>前面保留 <input id="setting-behind" type="number" min="2" max="10"></label><label>滚轮操作 <select id="setting-wheel"><option value="off">关闭</option><option value="alt">Alt + 滚轮</option><option value="direct">直接滚轮</option></select></label><label>数字键评分（0 = 10）<input id="setting-digits" type="checkbox"></label><label>跳过已完成作品 <input id="setting-skipDone" type="checkbox"></label><label>删除前确认 <input id="setting-confirmDelete" type="checkbox"></label></div>
 <h3>快捷键</h3><p class="muted">点击输入框后按键可绑定；多个键用英文逗号分隔。清空表示禁用。输入框中不会触发评分。</p><div class="settings-grid">${[['back','上一部'],['skip','跳过下一部'],['rate','按默认分评分'],['remove','删除收藏']].map(([a,t])=>`<label>${t}<input id="bind-${a}" autocomplete="off"></label>`).join('')}</div>
 <h3>面板按钮</h3><p class="muted">自定义名称、动作和顺序，勾选决定是否显示。留空名称使用自动文案。</p><div id="button-settings"></div>
 <div id="settings-error" role="alert"></div><div class="row"><button id="settings-save" class="primary">保存设置</button><button id="settings-cancel">返回</button><button id="settings-reset">恢复默认配置</button></div>
 <h3>数据备份</h3><p class="muted">导出当前账号的各列表进度和操作设置。导入只接受同一账号备份，不自动提交任何收藏。</p><div class="row"><button id="export">导出设置与进度</button><input id="import-file" type="file" accept="application/json,.json"><button id="import">导入备份</button></div>
 <h3>关于</h3><p>Bangumi 快速补标 v${VERSION}<br>${CREDIT}</p><p class="muted">适用于所有 Bangumi 用户，无需本校身份。仅使用当前站点登录状态，无遥测、不上传个人数据。滚轮向下只跳过，不评分。关闭面板继续后台保存；关闭网页后未完成任务下次继续核对。</p></section>
 <footer><span id="credit" class="muted">${CREDIT}</span></footer>
 <div id="modal" hidden><div id="modal-box" role="alertdialog" aria-modal="true"><p id="modal-text"></p><div class="row"><button id="modal-yes" class="danger">确认删除</button><button id="modal-no">取消</button></div></div></section></div>`;
 return {host,root,$:id=>root.getElementById(id)};
}
